#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
TOTAL_MINUTES=7

WORKFLOW_FILE=".github/workflows/security-review.yml"

# repo_slug — "owner/name" for this checkout, so we can deep-link its settings.
# Prefers gh (authoritative), falls back to parsing the git remote.
repo_slug() {
  local slug="" url=""
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    slug=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)
  fi
  if [[ -z "$slug" ]]; then
    url=$(git config --get remote.origin.url 2>/dev/null || true)
    if [[ "$url" =~ github\.com[:/]+([^/]+/[^/]+) ]]; then
      slug="${BASH_REMATCH[1]%.git}"
    fi
  fi
  printf '%s' "$slug"
}

banner "Add Anthropic's claude-code-security-review to this repo"

# ── 1 · Make sure a local secret cannot be committed ───────────────────────
stage "Protect local secrets" 1
say "Before writing any key to disk we make sure .env can never be committed."
say "This repo's .gitignore does not list .env today — for a security tool that"
say "would be an own-goal, so we fix it first."
if [[ -f .gitignore ]] && grep -qE '^\s*\.env\s*$' .gitignore; then
  note ".env is already ignored — nothing to do."
else
  if confirm "Add '.env' to .gitignore?"; then
    printf '\n# local secrets — never commit (added by scripts/setup-security-review.sh)\n.env\n' >> .gitignore
    printf '  %s✓ added%s .env → .gitignore\n' "$GREEN" "$RESET"
  else
    warn "Skipping. The key will NOT be written to .env; it will only go to GitHub."
    ENV_FILE=$(mktemp)   # keep write_env harmless: a throwaway outside the repo
    SKIPPED+=(".env is not gitignored — the API key was not persisted locally")
  fi
fi
pause

# ── 2 · The API key the Action needs ──────────────────────────────────────
stage "Anthropic API key" 2
say "The Action calls the Claude API, so it needs its own key."
open_url "https://console.anthropic.com/settings/keys"
step "Sign in, then click 'Create Key'."
step "Name it something like 'claude-code-security-review — <repo>'."
step "Copy the key (it is shown once; it starts with sk-ant-)."
ask_secret ANTHROPIC_API_KEY "Paste the API key (hidden):"
if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
  warn "No key entered — skipping. Re-run this wizard when you have one."
  SKIPPED+=("Anthropic API key (re-run this wizard)")
else
  write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
  # The Action's input is named claude-api-key and reads secrets.CLAUDE_API_KEY.
  set_secret CLAUDE_API_KEY "$ANTHROPIC_API_KEY"
fi
pause

# ── 3 · The workflow itself ───────────────────────────────────────────────
stage "Add the review workflow" 2
say "Writing $WORKFLOW_FILE — it runs the Action on every pull request and"
say "comments findings inline on the changed lines."
WRITE_WORKFLOW=yes
if [[ -f "$WORKFLOW_FILE" ]]; then
  warn "$WORKFLOW_FILE already exists."
  confirm "Overwrite it?" || WRITE_WORKFLOW=no
fi
if [[ "$WRITE_WORKFLOW" == yes ]]; then
  mkdir -p "$(dirname "$WORKFLOW_FILE")"
  cat > "$WORKFLOW_FILE" <<'YAML'
name: Security review

# Anthropic's LLM-based, semantics-aware review of the PR diff.
#
# It COMPLEMENTS this repo's deterministic engine rather than replacing it. Its findings are an
# ANALYSIS — non-deterministic, and in ClaudeGuardIL's own model an LLM/reviewer finding is capped
# at `likely` and can never reach `confirmed`, so it can never move the deterministic verdict. What
# it adds is the long tail the rules cannot reach: other languages (the engine does not parse
# Python) and deep semantic logic bugs (e.g. a session cookie whose HMAC is never verified).
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  security-review:
    name: claude security review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2

      - uses: anthropics/claude-code-security-review@main
        with:
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
          # PINNED ON PURPOSE. The Action's own default is claude-opus-4-1-20250805,
          # which is DEPRECATED and retires 2026-08-05 — leaving the default would work
          # for a few days and then break. Sonnet 5 is also the budget choice: near-Opus
          # quality on coding/agentic work at $3/$15 per MTok ($2/$10 introductory through
          # 2026-08-31) versus Opus 5's $5/$25 — roughly 2.5x more reviews per dollar.
          claude-model: claude-sonnet-5
          comment-pr: true
          upload-results: true
          # These directories hold DELIBERATELY vulnerable code used as fixtures: bench/wild/ is the
          # real-world benchmark corpus (real repos with real bugs, labelled on purpose) and
          # sample-vulnerable-app is the planted-P0 test fixture. Reviewing them is pure noise.
          exclude-directories: bench/wild,sample-vulnerable-app
YAML
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$WORKFLOW_FILE"
else
  note "Left the existing workflow untouched."
fi
pause

# ── 4 · Fork hardening (the Action's own requirement) ──────────────────────
stage "Harden against fork PRs" 1
warn "The Action is NOT hardened against prompt injection — its own README says"
warn "to only review trusted PRs. A malicious PR could otherwise steer the review."
SLUG=$(repo_slug)
if [[ -n "$SLUG" ]]; then
  open_url "https://github.com/${SLUG}/settings/actions"
else
  note "Could not detect the repo slug; open your repo's Settings → Actions manually."
  open_url "https://github.com/settings"
fi
step "Scroll to 'Fork pull request workflows from outside collaborators'."
step "Select 'Require approval for all external contributors'."
step "Click Save."
pause "Done? Press Enter."

# ── 5 · Commit and go live ────────────────────────────────────────────────
stage "Commit and go live" 1
say "Commit the workflow and push — it runs on the next pull request."
note "  git add $WORKFLOW_FILE .gitignore"
note "  git commit -m 'ci: add claude-code-security-review on pull requests'"
note "  git push"
say ""
say "Then open a PR and watch the 'claude security review' check."
note "Locally, Claude Code also ships a /security-review slash command that runs"
note "the same analysis without any of this CI setup."
pause "Press Enter when you're done."

finish
